# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ailantus-wa

on:
  push:
    branches:
      - feature/strapi
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: |
          npm install

      - name: Build Next.js in standalone mode
        run: |
          export __NEXT_PRIVATE_PREBUNDLED_REACT=next && npm run build

      - name: Zip all files for upload between jobs
        run: zip next.zip ./* .next .env -qr

      - name: Upload zipped standalone artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: standalone-nextjs
          path: next.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: standalone-nextjs
          path: .

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ailantus-wa"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2479A9DABF3A42CCBA17DC5B970A3AB8 }}
          package: next.zip # specify the package directory

  build-strapi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: cd into admin
        run: |
          cd admin

      - name: npm install, build, and test
        run: |
          cd admin
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip the 'admin' directory
        run: zip -r admin.zip admin/

      - name: Upload zipped artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: admin.zip

  deploy-strapi:
    runs-on: ubuntu-latest
    needs: build-strapi
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download zipped artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
          path: . # download to the current directory

      - name: Unzip the artifact
        run: unzip admin.zip

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ailantus-strapi"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_78527EAF7E134DA1A94CC60035F9A52F }}
          package: admin/
